on:
  - push
  - pull_request

name: Main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - run: |
          pip install poetry==1.2.2
          poetry install
          poetry run pre-commit run --all-files --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
        poetry-version:
          - '1.2.2'
          - '1.3.2'
          - '1.4.2'
          - '1.5.1'
          - '1.6.1'
          - '1.7.1'
          - '1.8.1'
        exclude:
          - python-version: '3.7'
            poetry-version: '1.6.1'
          - python-version: '3.7'
            poetry-version: '1.7.1'
          - python-version: '3.7'
            poetry-version: '1.8.1'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install pipx
          pipx install poetry==${{ matrix.poetry-version }}
          pipx install invoke

          poetry install --extras plugin
          invoke test
